openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://restaurant-api-nj73.onrender.com
    description: Production server on render
tags:
  - name: Menu
paths:
  /api/menu:
    $ref: paths/menu.yaml
  /api/menu/{id}:
    $ref: paths/menuById.yaml
