openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Users
    description: User-related endpoints
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/userId.yaml
