openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://restaurant-api-nj73.onrender.com
    description: Production server on render
tags:
  - name: Authentication
    description: Authentication-related endpoints
  - name: Users
    description: User-related endpoints
  - name: Menu
    description: Menu-related endpoints
  - name: Restaurants
    description: Restaurant-related endpoints
  - name: Reservations
    description: Reservation-related endpoints
 
paths:
  /api/auth/signup:
    $ref: paths/authsignup.yaml
  /api/auth/login:
    $ref: paths/authlogin.yaml
  /api/users:
    $ref: paths/users.yaml
  /api/users/me:
    $ref: paths/userId.yaml
  /api/users/{id}/reservations:
    $ref: paths/userReservationId.yaml
  /api/menu:
    $ref: paths/menu.yaml
  /api/menu/{id}:
    $ref: paths/menuById.yaml
  /api/restaurants:
    $ref: paths/restaurant.yaml
  /api/restaurants/{id}:
    $ref: paths/restaurantById.yaml
  /api/reservations:
    $ref: paths/reservationPath.yaml
  /api/reservations/{id}:
    $ref: paths/reservationById.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
