openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://restaurant-api-nj73.onrender.com
    description: Production server on render
tags:
  - name: Users
    description: User-related endpoints
  - name: Menu
  - name: Restaurants
    description: Restaurant-related endpoints
paths:
  /api/users:
    $ref: paths/users.yaml
  /api/users/{id}:
    $ref: paths/userId.yaml
  /api/menu:
    $ref: paths/menu.yaml
  /api/menu/{id}:
    $ref: paths/menuById.yaml
  /api/restaurants:
    $ref: paths/restaurant.yaml
  /api/restaurants/{id}:
    $ref: paths/restaurantById.yaml
  /api/reservation:
    $ref: paths/reservationPath.yaml
  /api/reservation/{id}:
    $ref: paths/reservationById.yaml
