openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
tags:
  - name: Users
    description: User-related endpoints
  - name: Menu
paths:
  /api/users:
    $ref: paths/users.yaml
  /api/users/{id}:
    $ref: paths/userId.yaml
  /api/menu:
    $ref: paths/menu.yaml
  /api/menu/{id}:
    $ref: paths/menuById.yaml
